version: '2'
services:
  articleservice:
    image: articleservice
    ports:
      - "8081:8081"

  basketservice:
    image: basketservice
    ports:
      - "8082:8082"

  checkoutservice:
    image: checkoutservice
    ports:
      - "8083:8083"

webservice:
    image: webservice
    ports:
      - "8080:80"
    depends_on:
      - articleservice
      - basketservice
      - checkoutservice
