version: '2'
services:
  webservice:
    image: unterstein/webservice
    ports:
      - "8080:80"
    depends_on:
      - articleservice
      - basketservice
      - checkoutservice

  articleservice:
    image: unterstein/articleservice
    ports:
      - "8081:8081"

  basketservice:
    image: unterstein/basketservice
    ports:
      - "8082:8082"

  checkoutservice:
    image: unterstein/checkoutservice
    ports:
      - "8083:8083"
