version: '2'
services:

  webservice:
    image: microservicelogging/webservice
    ports:
      - "8080:80"
    depends_on:
      - articleservice
      - basketservice
      - checkoutservice
      - elasticsearch

  checkoutservice:
    image: microservicelogging/checkoutservice
    ports:
      - "8083:8083"
    depends_on:
      - articleservice
      - basketservice
      - elasticsearch

  articleservice:
    image: microservicelogging/articleservice
    ports:
      - "8081:8081"
    depends_on:
      - elasticsearch

  basketservice:
    image: microservicelogging/basketservice
    ports:
      - "8082:8082"
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:5
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  elasticsearch:
    image: elasticsearch:5
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
