version: '2'
services:

  elasticsearch:
    image: unterstein/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - webservice

  webservice:
    image: unterstein/webservice
    ports:
      - "8080:80"
    depends_on:
      - articleservice
      - basketservice
      - checkoutservice

  articleservice:
    image: unterstein/articleservice
    ports:
      - "8081:8081"

  basketservice:
    image: unterstein/basketservice
    ports:
      - "8082:8082"

  checkoutservice:
    image: unterstein/checkoutservice
    ports:
      - "8083:8083"
